safe: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "slate"
      author: "Red Hat"

siteTitle: "Rel-Eng@Red Hat"
projectTitle: ""
tagline: "Documentation for Red Hat's release engineering projects available on GitHub"
owner: "Red Hat"
ownerEmail: jdcasey@redhat.com

markdown: redcarpet
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
